### ISSUE TITLE
关于WebNLG数据集关系数量

### ISSUE THREAD

**Issue by arrowfeng** [131250208/TPlinker-joint-extraction#11]
我使用set对训练集、校验集、测试集进行关系去重，最后只能得到216种关系，请问246种关系是如何得到的呢？

**Comment by 131250208** [comment]
> 我使用set对训练集、校验集、测试集进行关系去重，最后只能得到216种关系，请问246种关系是如何得到的呢？

你好，我在论文里提到了我们重新统计WebNLG和WebNLG*的关系数量分别是216和171，这两个数据集是直接从之前两个工作（ETL-Span和CasRel）沿用的，246是他们的错误统计。我估计他们直接把原始WebNLG的关系数量写在论文里了。
