### ISSUE TITLE
why special tokens such as cls, seq were not added?

### ISSUE THREAD

**Issue by Heaventrista** [131250208/TPlinker-joint-extraction#13]
as I know,  almost all bert models use special tokens , which was proved to have a better result that who did not. do you make  comparative experiments? could you give your explainations?

**Comment by 131250208** [comment]
We did not use them for the convenience of coding and did not do this comparison. If you want to use them, you have to rewrite the map functions (mapping upper triangular region to sequence), since adding cls and sep will change the offsets of other tokens.
