### ISSUE TITLE
中文数据集下面

### ISSUE THREAD

**Issue by zhangatao** [131250208/TPlinker-joint-extraction#14]
请问，你有在中文环境下跑过tplinker没，我在BuildData.ipynb中，看到你是在百度开放的信息抽取数据集，应该是做过实验吧。我按照readme的要求，把duie2的数据进行了转换，然后跑了一遍tplinker，发现训练速度非常慢，我的实验环境是gpu是v100。

**Comment by zhangatao** [comment]
这个是我现在的实验环境，以及参数设置
![image](https://user-images.githubusercontent.com/28706321/106704666-78b7c800-6627-11eb-9445-8dcf0a63a30d.png)

**Comment by 131250208** [comment]
因为序列长度是N^2，训练慢是正常现象。把训练的max_seq_len 控制在100左右即可，如果还是慢就是其他问题。

**Comment by 131250208** [comment]
> 请问，你有在中文环境下跑过tplinker没，我在BuildData.ipynb中，看到你是在百度开放的信息抽取数据集，应该是做过实验吧。我按照readme的要求，把duie2的数据进行了转换，然后跑了一遍tplinker，发现训练速度非常慢，我的实验环境是gpu是v100。

DuIE上跑过一次，没有提交结果，验证集上75左右。

**Comment by zhangatao** [comment]
好的，谢谢，我再试试

**Comment by zhangatao** [comment]
你好，我现在把训练的max_seq_len 控制在100，训练速度快了很多，谢谢🙏

**Comment by 131250208** [comment]
> 你好，我现在把训练的max_seq_len 控制在100，训练速度快了很多，谢谢🙏

好的

**Comment by lzh1998-jansen** [comment]
> 你有在中文环境下跑过tplinke
你在duie2数据集上的效果怎么样？

**Comment by lzh1998-jansen** [comment]
> 你好，我现在把训练的max_seq_len 控制在100，训练速度快了很多，谢谢🙏

![image](https://user-images.githubusercontent.com/61367424/209918932-08580d60-1af9-4fa2-915c-48c8f197838f.png)
head rel 和 tail rel，验证集上精度比较低
