### ISSUE TITLE
中文最终数据的额数据输入格式是怎样的？

### ISSUE THREAD

**Issue by lulia0228** [131250208/TPlinker-joint-extraction#15]
您好，中文最终模型输入的数据 char_span 和 token_span 分别指的是中文基于字排列的位置和基于分词后排列的位置吗？能简单给一下tplinker和tplinker++ 中文输入的示例吗？

**Comment by 131250208** [comment]
> 您好，中文最终模型输入的数据 char_span 和 token_span 分别指的是中文基于字排列的位置和基于分词后排列的位置吗？能简单给一下tplinker和tplinker++ 中文输入的示例吗？

char指的是字符，中文数据里不止有中文，简单的说list(text)得到的就是char。token指输入模型的最小单位，如果用word embedding， token就是word，比如： ["查", "尔", "斯", "·", "阿", "兰", "基", "斯", "（", "Charles", " ", "Ar", "á", "nguiz", "）"]; 如果用BERT，token就是subword， 比如：["查", "尔", "斯", "·", "阿", "兰", "基", "斯", "（", "[UNK]", "[UNK]", "[UNK]", "ng", "##ui", "##z", "）"]。模型输入不需要提供token_span，除了把编码器换成中文BERT，其他跟英文数据的处理是一样的。

**Comment by zhangatao** [comment]
但是中文分词之后，那个offset_mapping有点对应不上，会出现一些tok_span_error，请问这块应该怎么解决，把bert自带的tokenizer给替换了吗，

**Comment by lulia0228** [comment]
> > 您好，中文最终模型输入的数据 char_span 和 token_span 分别指的是中文基于字排列的位置和基于分词后排列的位置吗？能简单给一下tplinker和tplinker++ 中文输入的示例吗？
> 
> char指的是字符，中文数据里不止有中文，简单的说list(text)得到的就是char。token指输入模型的最小单位，如果用word embedding， token就是word，比如： ["查", "尔", "斯", "·", "阿", "兰", "基", "斯", "（", "Charles", " ", "Ar", "á", "nguiz", "）"]; 如果用BERT，token就是subword， 比如：["查", "尔", "斯", "·", "阿", "兰", "基", "斯", "（", "[UNK]", "[UNK]", "[UNK]", "ng", "##ui", "##z", "）"]。模型输入不需要提供token_span，除了把编码器换成中文BERT，其他跟英文数据的处理是一样的。

谢谢您的回复，已明白。我之前一直在纠结想用token span，想把中文里面的专有名词字典加到bert 的vocab中，但是这样好像不能直接起作用。请问您有尝试吗？或者说可不可以在transformer里面修改一些api来实现加入自己的长词，因为看到苏建林的bert4kera里面有这么做过。

**Comment by 131250208** [comment]
> > > 您好，中文最终模型输入的数据 char_span 和 token_span 分别指的是中文基于字排列的位置和基于分词后排列的位置吗？能简单给一下tplinker和tplinker++ 中文输入的示例吗？
> > 
> > 
> > char指的是字符，中文数据里不止有中文，简单的说list(text)得到的就是char。token指输入模型的最小单位，如果用word embedding， token就是word，比如： ["查", "尔", "斯", "·", "阿", "兰", "基", "斯", "（", "Charles", " ", "Ar", "á", "nguiz", "）"]; 如果用BERT，token就是subword， 比如：["查", "尔", "斯", "·", "阿", "兰", "基", "斯", "（", "[UNK]", "[UNK]", "[UNK]", "ng", "##ui", "##z", "）"]。模型输入不需要提供token_span，除了把编码器换成中文BERT，其他跟英文数据的处理是一样的。
> 
> 谢谢您的回复，已明白。我之前一直在纠结想用token span，想把中文里面的专有名词字典加到bert 的vocab中，但是这样好像不能直接起作用。请问您有尝试吗？或者说可不可以在transformer里面修改一些api来实现加入自己的长词，因为看到苏剑林的bert4kera里面有这么做过。

前面说错了，token_span是输入模型必须的，但是你自己处理数据的时候可以不用提供，用BuildData处理后会根据提供的char_span和offset_map生成对应的tok_span。
加入自己的词典我没有试过，BERT的vocab里有预留100个[unused]，你可以把新token加在这里。不过这些新token没有预训练过，不见得会有什么提升。如果想利用专有名词的信息，考虑在BERT编码后通过其他操作引入可能会好一点。

**Comment by 131250208** [comment]
> 但是中文分词之后，那个offset_mapping有点对应不上，会出现一些tok_span_error，请问这块应该怎么解决，把bert自带的tokenizer给替换了吗，

这个问题在目前的代码我没有处理，在处理中文数据时经常会遇到。这是由于BERT的切词跟标注的实体边界有冲突导致的，你可以基于BERT的tokenizer自定义一个新的tokenizer，先按实体边界把text切成多个片段，对于每个片段再用BERT的tokenizer切一遍，然后把每个片段对应的tokens和offset_map拼起来。

**Comment by zhangatao** [comment]
@131250208 感谢回复，我知道怎么处理了，🙏

**Comment by lulia0228** [comment]
@131250208 Thanks for your reply!  It helps a lot.

**Comment by paulcx** [comment]
处理中文数据集的[Trans_duie2.ipynb](https://github.com/131250208/TPlinker-joint-extraction/blob/dev/preprocess/Trans_duie2.ipynb)好像不大对？能否给个中文的示例？
`
{'text': '国内出版的东山魁夷散文作品有花山文艺出版社2001年《东山魁夷の世界》系列14本散文集，包括《与风景对话》、《听泉》、《我的窗》《探索日本之美》、《京洛四季——美之旅》、《通往唐招提寺之路》、《六只彩笔》、《中国纪行——水墨画的世界》、《德国纪行——马车啊，慢些走》、《奥地利纪行》、《北欧纪行》、《美与游历》、《我的留学时代》、《旅之环——自传抄》等', 'spo_list': [{'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '北欧纪行'}, {'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '探索日本之美'}, {'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '京洛四季'}]}
`

**Comment by 131250208** [comment]
> 处理中文数据集的[Trans_duie2.ipynb](https://github.com/131250208/TPlinker-joint-extraction/blob/dev/preprocess/Trans_duie2.ipynb)好像不大对？能否给个中文的示例？
> `{'text': '国内出版的东山魁夷散文作品有花山文艺出版社2001年《东山魁夷の世界》系列14本散文集，包括《与风景对话》、《听泉》、《我的窗》《探索日本之美》、《京洛四季——美之旅》、《通往唐招提寺之路》、《六只彩笔》、《中国纪行——水墨画的世界》、《德国纪行——马车啊，慢些走》、《奥地利纪行》、《北欧纪行》、《美与游历》、《我的留学时代》、《旅之环——自传抄》等', 'spo_list': [{'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '北欧纪行'}, {'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '探索日本之美'}, {'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '京洛四季'}]}`

我忘了那个有没有写完了，那些Trans_*都只是做转换数据格式的工作，逻辑很简单，你自己写一个也可以，跟英文的格式是一样的。这里有个例子：
{"id": "valid_6062", "text": "2013年，林依晨拍摄古装剧《兰陵王》获得极高好评，在此之后，林依晨似乎是“转战”电影行业，至今为止只拍摄了几部电影", "relation_list": [{"subject": "兰陵王", "object": "林依晨", "subj_char_span": [15, 18], "obj_char_span": [6, 9], "predicate": "主演", "subj_tok_span": [12, 15], "obj_tok_span": [3, 6]}, {"subject": "兰陵王", "object": "林依晨", "subj_char_span": [15, 18], "obj_char_span": [31, 34], "predicate": "主演", "subj_tok_span": [12, 15], "obj_tok_span": [28, 31]}], "entity_list": [{"text": "兰陵王", "type": "影视作品", "char_span": [15, 18], "tok_span": [12, 15]}, {"text": "林依晨", "type": "人物", "char_span": [6, 9], "tok_span": [3, 6]}, {"text": "林依晨", "type": "人物", "char_span": [31, 34], "tok_span": [28, 31]}]}

**Comment by LawsonAbs** [comment]
> 处理中文数据集的[Trans_duie2.ipynb](https://github.com/131250208/TPlinker-joint-extraction/blob/dev/preprocess/Trans_duie2.ipynb)好像不大对？能否给个中文的示例？
> `{'text': '国内出版的东山魁夷散文作品有花山文艺出版社2001年《东山魁夷の世界》系列14本散文集，包括《与风景对话》、《听泉》、《我的窗》《探索日本之美》、《京洛四季——美之旅》、《通往唐招提寺之路》、《六只彩笔》、《中国纪行——水墨画的世界》、《德国纪行——马车啊，慢些走》、《奥地利纪行》、《北欧纪行》、《美与游历》、《我的留学时代》、《旅之环——自传抄》等', 'spo_list': [{'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '北欧纪行'}, {'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '探索日本之美'}, {'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '京洛四季'}]}`

这个文件现在可以直接用吗？

**Comment by AI-Mart** [comment]
作者的工作非常棒，有个问题咨询下，针对百度的中文数据集，请问tplink plus的输入数据的格式和tplink输入数据的格式有什么区别？是不是只要吧tplink的ent2id.json 的{"DEFAULT": 0}换成对应的实际实体类别
tplink训练数据集如下，把里面的 "type": "DEFAULT"换成对应的实体实际类别就是tplink plus的输入格式了？
[{"text": "《邪少兵王》是冰火未央写的网络小说连载于旗峰天下", "id": "train_0", "relation_list": [{"subject": "邪少兵王", "object": "冰火未央", "subj_char_span": [1, 5], "obj_char_span": [7, 11], "predicate": "作者", "subj_tok_span": [1, 5], "obj_tok_span": [7, 11]}], "entity_list": [{"text": "邪少兵王", "type": "DEFAULT", "char_span": [1, 5], "tok_span": [1, 5]}, {"text": "冰火未央", "type": "DEFAULT", "char_span": [7, 11], "tok_span": [7, 11]}]}, {"text": "GV-971由中国海洋大学、中国科学院上海药物研究所（下称“上海药物所”）和上海绿谷制药有限公司（下称“绿谷制药”）联合研发，不同于传统靶向抗体药物，GV-971是从海藻中提取的海洋寡糖类分子", "id": "train_1", "relation_list": [{"subject": "中国科学院上海药物研究所", "object": "上海药物所", "subj_char_span": [14, 26], "obj_char_span": [30, 35], "predicate": "简称", "subj_tok_span": [12, 24], "obj_tok_span": [28, 33]}], "entity_list": [{"text": "中国科学院上海药物研究所", "type": "DEFAULT", "char_span": [14, 26], "tok_span": [12, 24]}, {"text": "上海药物所", "type": "DEFAULT", "char_span": [30, 35], "tok_span": [28, 33]}]}]

**Comment by 131250208** [comment]
> > 处理中文数据集的[Trans_duie2.ipynb](https://github.com/131250208/TPlinker-joint-extraction/blob/dev/preprocess/Trans_duie2.ipynb)好像不大对？能否给个中文的示例？
> > `{'text': '国内出版的东山魁夷散文作品有花山文艺出版社2001年《东山魁夷の世界》系列14本散文集，包括《与风景对话》、《听泉》、《我的窗》《探索日本之美》、《京洛四季——美之旅》、《通往唐招提寺之路》、《六只彩笔》、《中国纪行——水墨画的世界》、《德国纪行——马车啊，慢些走》、《奥地利纪行》、《北欧纪行》、《美与游历》、《我的留学时代》、《旅之环——自传抄》等', 'spo_list': [{'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '北欧纪行'}, {'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '探索日本之美'}, {'predicate': '作者', 'object_type': {'@value': '人物'}, 'subject_type': '图书作品', 'object': {'@value': '东山魁夷'}, 'subject': '京洛四季'}]}`
> 
> 我忘了那个有没有写完了，那些Trans_*都只是做转换数据格式的工作，逻辑很简单，你自己写一个也可以，跟英文的格式是一样的。这里有个例子： {"id": "valid_6062", "text": "2013年，林依晨拍摄古装剧《兰陵王》获得极高好评，在此之后，林依晨似乎是“转战”电影行业，至今为止只拍摄了几部电影", "relation_list": [{"subject": "兰陵王", "object": "林依晨", "subj_char_span": [15, 18], "obj_char_span": [6, 9], "predicate": "主演", "subj_tok_span": [12, 15], "obj_tok_span": [3, 6]}, {"subject": "兰陵王", "object": "林依晨", "subj_char_span": [15, 18], "obj_char_span": [31, 34], "predicate": "主演", "subj_tok_span": [12, 15], "obj_tok_span": [28, 31]}], "entity_list": [{"text": "兰陵王", "type": "影视作品", "char_span": [15, 18], "tok_span": [12, 15]}, {"text": "林依晨", "type": "人物", "char_span": [6, 9], "tok_span": [3, 6]}, {"text": "林依晨", "type": "人物", "char_span": [31, 34], "tok_span": [28, 31]}]}

是的，我这里给过例子了。另外ent2id在BuildData里自动生成，不需要手动改

**Comment by pengfan7758258** [comment]
> 
如果这样做是不是会造成训练和推理的不一致，因为在推理阶段我们并没有实体的边界这一说

**Comment by pengfan7758258** [comment]
> > 但是中文分词之后，那个offset_mapping有点对应不上，会出现一些tok_span_error，请问这块应该怎么解决，把bert自带的tokenizer给替换了吗，
> 
> 这个问题在目前的代码我没有处理，在处理中文数据时经常会遇到。这是由于BERT的切词跟标注的实体边界有冲突导致的，你可以基于BERT的tokenizer自定义一个新的tokenizer，先按实体边界把text切成多个片段，对于每个片段再用BERT的tokenizer切一遍，然后把每个片段对应的tokens和offset_map拼起来。

这么操作的话是不是造成了训练和推理的不一致，因为在推理阶段我们并没有实体也就没有实体边界这一说，也就会产生差异

**Comment by YuJiaYi1412** [comment]
> 作者的工作非常棒，有个问题咨询下，针对百度的中文数据集，请问tplink plus的输入数据的格式和tplink输入数据的格式有什么区别？是不是只要吧tplink的ent2id.json 的{"DEFAULT": 0}换成对应的实际实体类别 tplink训练数据集如下，把里面的 "type": "DEFAULT"换成对应的实体实际类别就是tplink plus的输入格式了？ [{"text": "《邪少兵王》是冰火未央写的网络小说连载于旗峰天下", "id": "train_0", "relation_list": [{"subject": "邪少兵王", "object": "冰火未央", "subj_char_span": [1, 5], "obj_char_span": [7, 11], "predicate": "作者", "subj_tok_span": [1, 5], "obj_tok_span": [7, 11]}], "entity_list": [{"text": "邪少兵王", "type": "DEFAULT", "char_span": [1, 5], "tok_span": [1, 5]}, {"text": "冰火未央", "type": "DEFAULT", "char_span": [7, 11], "tok_span": [7, 11]}]}, {"text": "GV-971由中国海洋大学、中国科学院上海药物研究所（下称“上海药物所”）和上海绿谷制药有限公司（下称“绿谷制药”）联合研发，不同于传统靶向抗体药物，GV-971是从海藻中提取的海洋寡糖类分子", "id": "train_1", "relation_list": [{"subject": "中国科学院上海药物研究所", "object": "上海药物所", "subj_char_span": [14, 26], "obj_char_span": [30, 35], "predicate": "简称", "subj_tok_span": [12, 24], "obj_tok_span": [28, 33]}], "entity_list": [{"text": "中国科学院上海药物研究所", "type": "DEFAULT", "char_span": [14, 26], "tok_span": [12, 24]}, {"text": "上海药物所", "type": "DEFAULT", "char_span": [30, 35], "tok_span": [28, 33]}]}]

小白提问，为啥你的数据char_span和tok_span一样？作者给的示例不是不一样吗
