### ISSUE TITLE
关于loss的权重？

### ISSUE THREAD

**Issue by YYGe01** [131250208/TPlinker-joint-extraction#16]
作者您好，感谢分享代码。

我看训练时对两个loss有不同的权重：loss_weights = {"ent": w_ent, "rel": w_rel}。刚开始w_ent很大，后面逐渐降低。

这里我想问下这个权重的选择，是靠经验，还是有什么原理吗？谢谢！

**Comment by 131250208** [comment]
> 作者您好，感谢分享代码。
> 
> 我看训练时对两个loss有不同的权重：loss_weights = {"ent": w_ent, "rel": w_rel}。刚开始w_ent很大，后面逐渐降低。
> 
> 这里我想问下这个权重的选择，是靠经验，还是有什么原理吗？谢谢！

先学实体再学关系（先易后难），有助于加速收敛，不调权重也可以，不过需要跑更多轮才能出分数。当初只是尝试一下，然后发现确实可以更快收敛。
