### ISSUE TITLE
输出能否加上实体类型

### ISSUE THREAD

**Issue by minfei1998** [131250208/TPlinker-joint-extraction#18]
数据集中给的实体类型为什么都是DEFAULT，输出的时候能够预测实体类型并输出吗

**Comment by 131250208** [comment]
因为实验数据里没有实体类型，所以TPLinker里没有添加这个部分。如果你需要这个功能可以直接使用TPLinkerPlus，或者自行修改TPLinker的EH-to-ET编解码过程使其具有这个能力。
