### ISSUE TITLE
关系类别数量不平衡的问题

### ISSUE THREAD

**Issue by liutianling** [131250208/TPlinker-joint-extraction#19]
您好，再次感谢您分享的这么棒的工作。
有个问题请假下，我查看了 nyt 训练数据的关系类别，简单统计了下，发现关系类别的数量分布不平衡，有的差别很大，不知道您有没有特别处理这方面问题，或者这个问题最模型实际效果有没有影响。
如果我没有看错的话，训练以及测试过程中的评估都是用的所有类别的平均准确率，也就是好像没有考虑关系类别的问题。

            {'/business/company/advisors': 44,
             '/business/company/founders': 812,
             '/business/company/industry': 2,
             '/business/company/major_shareholders': 283,
             '/business/company/place_founded': 409,
             '/business/company_shareholder/major_shareholder_of': 283,
             '/business/person/company': 5614,
             '/location/administrative_division/country': 7303,
             '/location/country/administrative_divisions': 7303,
             '/location/country/capital': 8366,
             '/location/location/contains': 54669,
             '/location/neighborhood/neighborhood_of': 6018,
             '/people/deceased_person/place_of_death': 1964,
             '/people/ethnicity/geographic_distribution': 58,
             '/people/ethnicity/people': 22,
             '/people/person/children': 453,
             '/people/person/ethnicity': 22,
             '/people/person/nationality': 8599,
             '/people/person/place_lived': 6887,
             '/people/person/place_of_birth': 3098,
             '/people/person/profession': 2,
             '/people/person/religion': 69,
             '/sports/sports_team/location': 328,
             '/sports/sports_team_location/teams': 328})

**Comment by 131250208** [comment]
你好，我目前没有做过这方面的分析实验，实验数据集的划分也是沿用之前的工作。如果测试集的类别分布与训练集时很相近的，那么对整体效果不会有太大影响。建议参考其他研究类别不均衡问题的工作。
