### ISSUE TITLE
.yaml format

### ISSUE THREAD

**Issue by WatsonWangZh** [131250208/TPlinker-joint-extraction#2]
Will you give one for reference, thanks.

**Comment by WatsonWangZh** [comment]
what's the all test*.json refer to? please make it clear, thanks.

**Comment by 131250208** [comment]
> Will you give one for reference, thanks.

Yes, we forgot to provide them since we were planning to change all .yaml configuration files to .py format. Now, they are uploaded.

**Comment by 131250208** [comment]
> what's the all test*.json refer to? please make it clear, thanks.

They are subsets of the original test set (test_triplets.json). We split the test set by overlapping patterns and triplet numbers. For more details, you could see Table 1 in [our paper](https://drive.google.com/file/d/1fCmbBi_4mzFmzLS-ovtEyRigiM7wWigM/view?usp=sharing), or see [the paper of CasRel](https://arxiv.org/abs/1909.03227). We follow their splitting methods.
