### ISSUE TITLE
[dataset_name]_star与[dataset_name]两个数据集的差异是什么？存在这两个数据集的意义是什么？

### ISSUE THREAD

**Issue by HuizhaoWang** [131250208/TPlinker-joint-extraction#20]
您好，感谢分享这么优秀的工作！刚入此任务的小白，有几个关于数据集的疑问，麻烦您帮忙解惑，不甚感激。
1、nyt与nyt_star,webnlg与webnlg_star分别有什么差异？
2、[dataset_name]_star是经过[dataset_name]转化而来的吗？如果是的话，转化得到新数据集的意义是什么？
3、如果将该方法（使用bert作为encoder方法）应用于中文数据集（每一条文本句子可能掺杂数字和英文等），有什么需要注意的地方吗？
4、这两数据集都是没有提供实体类型，有没有提供这一信息的相关数据集?

期待您的回复！！！！

**Comment by arrowfeng** [comment]
你好，为什么WebNLG和WebNLG*的关系数量也不一样呀？区别不就是只标一个实体的单词和一个实体的所有单词吗？为什么会影响到关系数量。有点不理解。。。

**Comment by 131250208** [comment]
@arrowfeng WebNLG是用[ETL-span](https://github.com/yubowen-ph/JointER/tree/master/dataset/WebNLG/data)处理的数据，WebNLG*使用[CasRel](https://github.com/weizhepei/CasRel/tree/master/data)，可能是CasRel做了一些合并吧，我们只是沿用数据方便公平对比。
