### ISSUE TITLE
训练和测试时max_len的差异

### ISSUE THREAD

**Issue by liuyaduo** [131250208/TPlinker-joint-extraction#22]
您好，

您的代码中，在train_config中设置max_seq_len为128，在eval_config中设置max_seq_len为512。
因此，我想请教以下问题：
1.在训练时将长句划分为长度128以内的短句训练；测试阶段，长度超过128的长句子不会分割，是否会存在问题?
2.如此训练的模型是否只适合短句而不适合长句？

谢谢

**Comment by 131250208** [comment]
@liuyaduo 无论训练阶段还是测试阶段，文本都会采用滑窗的方式切割成长度为max_seq_len。训练阶段，建议设置不超过100的max_seq_len，以免训练时间过长。很多关系的语义表述都在一个较短的范围内，我有尝试过将训练的max_seq_len设置成64，对测试集的上的性能也并没什么大的影响。模型的性能不受限于长句或短句，而受限于关系中两个实体的距离，如果数据集中大多数关系的两个实体跨度都很大，比如都超过100个单词，则该模型不适用。

**Comment by 131250208** [comment]
@liuyaduo 测试阶段的max_seq_len设置成512是为了减少切断真实关系的情况，训练阶段不用担心这个问题，因为滑窗机制会缓解这种切断带来的训练数据损失，即使切断了少量的关系，在训练数据充足的情况下对训练效果的影响也是很小的。
