### ISSUE TITLE
使用tplinker-plus时的GPU内存问题

### ISSUE THREAD

**Issue by minfei1998** [131250208/TPlinker-joint-extraction#23]
我使用tplinker-plus的模型代码时，我的GPU采用了最大的GeForce RTX 3090,但是依然出现cuda内存不够的情况。而使用tplinker模型则不会报错。请问如何解决在tplinker-plus模型中的问题，有什么办法吗？

**Comment by 131250208** [comment]
请提供你的训练参数设置

**Comment by minfei1998** [comment]
{
   “shaking_type”:"cln_plus",
    "":"",
    "":"",
}

**Comment by minfei1998** [comment]
{
“shaking_type”:"cln_plus",
"inner_enc_type":"lstm",
"match_pattern":"whole_text",
"lr":"5e-05",
"batch_size":"32",
"epochs":"100",
"seed":"2333",
"log_interval":"10",
"max_seq_len":"128",
"sliding_len":"20",
"scheduler":"CAWR",
"ghm":false,
"tok_pair_sample_rate":1,
"T_mult":"1",
"rewarm_epoch_num":"2"
}

**Comment by 131250208** [comment]
@minfei1998 这个参数跟我设的是一样的，跑起来应该是没问题的，但确实很慢，消耗显存多。主要原因是batch和max_seq_len设太大，建议batch_size=[16, 32]，max_seq_len=[64, 100]，先从最小的开始试，应该也是可以得到不错的效果。减小max_seq_len可以大幅度减小需要的显存。

**Comment by 131250208** [comment]
![image](https://user-images.githubusercontent.com/7437595/111246219-d553cd00-8640-11eb-8b73-3a7754bdc91b.png)
这是你这个参数的log

**Comment by minfei1998** [comment]
好的，谢谢，降低max_len后问题已经解决了
