### ISSUE TITLE
BuildData 处理不了中文，求助

### ISSUE THREAD

**Issue by passion765** [131250208/TPlinker-joint-extraction#25]

**Comment by 131250208** [comment]
我想你已经找到相关的issue了

**Comment by passion765** [comment]
> 我想你已经找到相关的issue了

作者能建个群吗

**Comment by 131250208** [comment]
> > 我想你已经找到相关的issue了
> 
> 作者能建个群吗

有什么问题就在issue和邮件问吧，没有建群的打算

**Comment by passion765** [comment]
@131250208 能把训练百度三元组的日志贴一下吗，我这个训练f1 一直上不去。

**Comment by 131250208** [comment]
![image](https://user-images.githubusercontent.com/7437595/112405333-0755e500-8d4d-11eb-90bb-c4c301a3896e.png)
![image](https://user-images.githubusercontent.com/7437595/112405403-294f6780-8d4d-11eb-8c27-ad91cb5759d7.png)
![image](https://user-images.githubusercontent.com/7437595/112405439-39ffdd80-8d4d-11eb-9daa-0e4fe75989c4.png)

**Comment by 131250208** [comment]
@passion765 检查训练参数、预处理、BERT路径

**Comment by passion765** [comment]
@131250208  刚看到你的dev仓库有数据DuIE2转换，之前都是研究的master仓库， 您可以把你的DuIE2  数据集分享一下吗 ，我的数据集格式还不太一样，谢谢

**Comment by guanxichouqu** [comment]
> @131250208 能把训练百度三元组的日志贴一下吗，我这个训练f1 一直上不去。

你好请问一下中文数据集需要处理哪些 我刚入门的小白 不太懂 谢谢啦
