### ISSUE TITLE
是否可以加入外部知识？

### ISSUE THREAD

**Issue by liutianling** [131250208/TPlinker-joint-extraction#28]
再次感谢您分享的工作！
我这里有个例子，以下结果是用nyt模型训练，然后单条预测的结果：
{'rels': [{'id': '0', 'text': 'US Election 2020: Trump COVID-19 positive: What next?', 'relation_list': [{'subject': 'US', 'object': 'Trump', 'subj_tok_span': [0, 1], 'obj_tok_span': [4, 5], 'subj_char_span': [0, 2], 'obj_char_span': [18, 23], 'predicate': '/location/location/contains'}]}]}
从这个例子来看，模型应该是把 Trump 当做一个地名了。假设模型能正确识别Trump为一个人，然后进行关系预测，也很难预测总统关系出来。
我想问的是，有没有什么办法让模型学习一些知识？比如这个例子，告诉模型Trump是美国总统。当然，最后对结果进行外部知识检索匹配是一个方法！

**Comment by 131250208** [comment]
从你的例子看，主要是上下文信息太少，不足以推断出是总统。如果有其他充足的语料训练出Trump和US的共现关系，这一条也是抽得出来的，那相当于让模型记住了Trump是US的总统。另外可以尝试将text输入搜索引擎检索出相关信息拼接在原文后面作为上下文的补充。

**Comment by liutianling** [comment]
明白了，谢谢！
还有另外一个问题，train.py 504行，loss_weights中w_ent和w_rel为什么这么计算，看数值，好像是训练前期更加关注ent的损失，后期更加关注rel的损失，是这样吗？谢谢！

**Comment by 131250208** [comment]
> 明白了，谢谢！
> 还有另外一个问题，train.py 504行，loss_weights中w_ent和w_rel为什么这么计算，看数值，好像是训练前期更加关注ent的损失，后期更加关注rel的损失，是这样吗？谢谢！

是的，ent的学习比rel容易并且对rel有指导作用，实验证明这样收敛速度快一点，可以节省训练时间，对最后的性能并无太大影响。

**Comment by liutianling** [comment]
非常感谢您的及时回复，谢谢。
