### ISSUE TITLE
有几点疑问请教

### ISSUE THREAD

**Issue by YYGe01** [131250208/TPlinker-joint-extraction#29]
非常感谢作者开源，很棒的模型架构。

1、第一个问题是关于数据集。
训练集有这么一个样本：

> 'text': '李治即位后，萧淑妃受宠，王皇后为了排挤萧淑妃，答应李治让身在感业寺的武则天续起头发，重新纳入后宫'

其中spo为(李治，妻子，萧淑妃)，妻子为关系。这里萧淑妃和李治分别有两个。

我的问题是，在构建训练集时，是否有必要把所有位置的 s 和 o 都考虑到呢，如下可以构建4个spo，不知道这样去训练是否有问题。因为如果4个spo全部训练，预测的时候也会需要有预测4个spo的能力，是否会加大预测难度。

或者只选取第一次出现的实体，是否更好点呢？

> {'predicate': '妻子', 'subject': '李治', 'subj_tok_span': [0, 2], 'object': '萧淑妃', 'obj_tok_span': [6, 9]}, 
> {'predicate': '妻子', 'subject': '李治', 'subj_tok_span': [0, 2], 'object': '萧淑妃', 'obj_tok_span': [19, 22]}, 
> {'predicate': '妻子', 'subject': '李治', 'subj_tok_span': [25, 27], 'object': '萧淑妃', 'obj_tok_span': [6, 9]}, 
> {'predicate': '妻子', 'subject': '李治', 'subj_tok_span': [25, 27], 'object': '萧淑妃', 'obj_tok_span': [19, 22]}

2、中文数据集的tokenizer

我这边把作者在英文数据集的代码改造成了中文，为了简单，我去除了wordpiece，直接改用一个字符一个token。
比如
原句: "●1981年2月27日"，直接按单个字符切分成：['●', '1', '9', '8', '1', '年', '2', '月', '2', '7', '日']
其实这种方式，我感觉没啥问题，不知道作者有什么看法呢？

3、关于训练复杂度的问题。

我看self.shaking_ind2matrix_ind是样本长度的排列组合，像作者推荐样本长度是100，那么会有5050的span。复杂度为n^2。

因为训练时长的关系，然后我这边想对span进行剪枝，比如设定一个实体span的长度限制20，这样的话，span的总数会少得多，我就可以放心的把样本长度加长，不知道作者有没有试过呢，这种剪枝方案对性能会有影响吗？

**Comment by 131250208** [comment]
1. 构建4个spo更好，因为任意一对都有可能是表达了这种关系的语义，而你不知道那些是哪些不是，只取第一次出现的实体反而有可能降低数据集的标注质量。预测时并不会加大预测难度，如果训练集没有给出span，一般测评时只要求text对即可，也就是你预测出4个中的任意一对且text完全正确即可。
2. 这样做一般效果会变差，BERT是以wordpiece为最小单位去做预训练的，你用自己的切词方法会导致很多已经得到充分预训练的token向量没有得到充分利用（比如中文中的英文单词，以及特殊含义的数字组合），也就是说你放弃了这部分“先验知识”而选择重新训练。另一个方面，你这样加大了序列长度，导致效率降低。
3. 实体识别部分可以这样做，但关系部分不推荐，因为关系的跨度有时很大，可能超过你设置的这个span。

**Comment by mkzzz** [comment]
> 1. 构建4个spo更好，因为任意一对都有可能是表达了这种关系的语义，而你不知道那些是哪些不是，只取第一次出现的实体反而有可能降低数据集的标注质量。预测时并不会加大预测难度，如果训练集没有给出span，一般测评时只要求text对即可，也就是你预测出4个中的任意一对且text完全正确即可。
> 2. 这样做一般效果会变差，BERT是以wordpiece为最小单位去做预训练的，你用自己的切词方法会导致很多已经得到充分预训练的token向量没有得到充分利用（比如中文中的英文单词，以及特殊含义的数字组合），也就是说你放弃了这部分“先验知识”而选择重新训练。另一个方面，你这样加大了序列长度，导致效率降低。
> 3. 实体识别部分可以这样做，但关系部分不推荐，因为关系的跨度有时很大，可能超过你设置的这个span。

哈喽，作者你好，关于这里面的第一个问题，我有些疑问，构建4个spo，我们假设当中有1对spo是表达了关系语义的，另外3对spo没有表达关系语义，这时如果另一个句子中只存在了没有表达关系语义的3个spo，那么模型也会预测出来这个spo的关系吗？如果能预测出来，是否可说明模型有些问题？

**Comment by 131250208** [comment]
@mkzzz 这样做是为了方便，并且对预测效果影响不大。两个原因：1）大部分情况下表达了关系语义的spo要多于没有表达关系语义的spo 2）没表达关系语义（表达1）的spo是在上下文中出现了至少一个表达了这种关系（表达2）的spo的情况下才被标注的，所以并不能完全归为错误的标注。如果另一段文本中出现了类似的表达1，但前后文缺少表达2，模型将该spo抽取出来的概率并不大。
如果抽取出来这种错误的spo，也并不能说是模型的问题，更准确地说，是数据标注引入的问题。

**Comment by mkzzz** [comment]
> @mkzzz 这样做是为了方便，并且对预测效果影响不大。两个原因：1）大部分情况下表达了关系语义的spo要多于没有表达关系语义的spo 2）没表达关系语义（表达1）的spo是在上下文中出现了至少一个表达了这种关系（表达2）的spo的情况下才被标注的，所以并不能完全归为错误的标注。如果另一段文本中出现了类似的表达1，但前后文缺少表达2，模型将该spo抽取出来的概率并不大。
> 如果抽取出来这种错误的spo，也并不能说是模型的问题，更准确地说，是数据标注引入的问题。

明白了，谢谢回复～
