### ISSUE TITLE
可以用ACE2005数据集来复现代码嘛？

### ISSUE THREAD

**Issue by zhangmy0813** [131250208/TPlinker-joint-extraction#30]

**Comment by 131250208** [comment]
任何关系抽取的数据都可以，自行转换格式即可

**Comment by zhangmy0813** [comment]
ACE2005数据集也可以用BuildData.ipynb来构造数据集嘛？谢谢~

**Comment by 131250208** [comment]
参考readme里build data部分的数据格式，以及最后一句话

**Comment by zhangmy0813** [comment]
好的，谢谢~

**Comment by zhangmy0813** [comment]
可以问一下Trans_ace05.ipynb的作用是什么嘛？

**Comment by 131250208** [comment]
那个没什么用，之前在尝试做事件抽取

**Comment by guanxichouqu** [comment]
> 可以问一下Trans_ace05.ipynb的作用是什么嘛？

你好 请问一下用自己的数据集需要改什么地方吗 我是刚入门的小白 希望在自己中文数据集上进行训练 可以请教一下相关经验吗
