### ISSUE TITLE
请问TPlinker-plus和原版有什么区别？

### ISSUE THREAD

**Issue by transformerzhou** [131250208/TPlinker-joint-extraction#4]

**Comment by 131250208** [comment]
Different model structure and loss function. Mitigated label bias，speeded up the convergence, and improved the results slightly.

**Comment by WatsonWangZh** [comment]
When will you make the tpliner-plus paper public?

**Comment by 131250208** [comment]
> When will you make the tpliner-plus paper public?

Maybe in around 1 or 2 months.  But it can not be guaranteed because I will be very busy with my Ph.D. application next several months.

**Comment by WatsonWangZh** [comment]
> > When will you make the tpliner-plus paper public?
> 
> Maybe in around 1 or 2 months. But it can not be guaranteed because I will be very busy with my Ph.D. application next several months.

Is it the same as the code you make public?

**Comment by 131250208** [comment]
> > > When will you make the tpliner-plus paper public?
> > 
> > 
> > Maybe in around 1 or 2 months. But it can not be guaranteed because I will be very busy with my Ph.D. application next several months.
> 
> Is it the same as the code you make public?

The results in the report can be reproduced by the public code, but we might add something else in the final paper.
