### ISSUE TITLE
请问模型在这几个数据集上训练的时间大致是多久，实验的环境是怎么样的？

### ISSUE THREAD

**Issue by jxyxiangyu** [131250208/TPlinker-joint-extraction#5]
对显卡显存要求高吗？训练时间大致多久？

**Comment by jxyxiangyu** [comment]
按您在论文中说的超参数的设置，模型大概占多大的显存呢，v100是32G显存还是16G显存的呢

**Comment by 131250208** [comment]
我的实验环境，16G，在不共用显卡且CPU较空闲的情况下，24小时内可以达到。
可以按以下参数设置，NYT上将batch_size改成24，loss_weight_recover_steps我记不太清了，改成6000-12000之间应该差别不大，这个主要是起到加速训练的效果。
如果嫌慢可以将shaking_type改成cat_plus

-------------WebNLG-----------------
T_mult: 1
rewarm_epoch_num: 2
batch_size: 6
dist_emb_size: -1
ent_add_dist: false
rel_add_dist: false
epochs: 200
log_interval: 10
loss_weight_recover_steps: 6000
lr: 0.00005
match_pattern: only_head_text
max_seq_len: 100
sliding_len: 20
scheduler: CAWR
seed: 2333
shaking_type: cat

**Comment by 131250208** [comment]
> 按您在论文中说的超参数的设置，模型大概占多大的显存呢，v100是32G显存还是16G显存的呢

cat的情况，WebNLG占4.5G，NYT占8.5G。cat_plus会更高，但16G够用

**Comment by jxyxiangyu** [comment]
感谢您的回答
