### ISSUE TITLE
断错误

### ISSUE THREAD

**Issue by liutianling** [131250208/TPlinker-joint-extraction#6]
![image](https://user-images.githubusercontent.com/32763852/99375167-5fdc2800-28fe-11eb-8513-ce2f097c3156.png)

非常感谢您的分享！
我这边运行代码的时候，直接断错误，没有其他报错，这个是

**Comment by pvcastro** [comment]
@liutianling I ran into the same problem. Updating pytorch seems to have worked for me.

**Comment by 131250208** [comment]
> ![image](https://user-images.githubusercontent.com/32763852/99375167-5fdc2800-28fe-11eb-8513-ce2f097c3156.png)
> 
> 非常感谢您的分享！
> 我这边运行代码的时候，直接断错误，没有其他报错，这个是

我这边没遇到这个错误，可能是环境的问题。最近太忙了，你可以先试试 @pvcastro说的，更新一下pytorch版本。
I did not meet this error before. It may be a problem with your environment. You might want to try @pvcastro 's solution. I am very busy recently. So, I may be slow to reproduce the error and fix it. If updating does not work, please continue to report your error. I will try to fix it after I finish my work.

**Comment by 131250208** [comment]
> @liutianling I ran into the same problem. Updating pytorch seems to have worked for me.

Thank you!

**Comment by liutianling** [comment]
@pvcastro @131250208 Thank you so much.
It works for me when i update the torch from 1.4 to 1.5 .
Thanks again..
